apiVersion: dataplane.openstack.org/v1beta1
kind: OpenStackDataPlaneService
metadata:
  name: ovn-bgp-agent
spec:
  playbook: osp.edpm.ovn_bgp_agent
  dataSources:
    - secretRef:
        name: neutron-ovn-agent-neutron-config
    - configMapRef:
        name: ovn-bgp-agent-extra-config
        optional: true
  tlsCerts:
    default:
      contents:
      - dnsnames
      - ips
      networks:
      - ctlplane
      issuer: osp-rootca-issuer-ovn
      keyUsages:
        - digital signature
        - key encipherment
        - server auth
        - client auth
  caCerts: combined-ca-bundle
  containerImageFields:
  - EdpmOvnBgpAgentImage
  edpmServiceType: ovn-bgp-agent
