apiVersion: dataplane.openstack.org/v1beta1
kind: OpenStackDataPlaneService
metadata:
  labels:
    app.kubernetes.io/name: openstackdataplaneservice
    app.kubernetes.io/instance: openstackdataplaneservice-derive-pci-devicespec
    app.kubernetes.io/part-of: openstack-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: openstack-operator
  name: derive-pci-devicespec
spec:
  playbook: osp.edpm.sriov_derive_device_spec
