apiVersion: dataplane.openstack.org/v1beta1
kind: OpenStackDataPlaneService
metadata:
  name: neutron-sriov
spec:
  playbook: osp.edpm.neutron_sriov
  dataSources:
    - secretRef:
        name: neutron-sriov-agent-neutron-config
    - configMapRef:
        name: neutron-sriov-extra-config
        optional: true
  caCerts: combined-ca-bundle
  containerImageFields:
  - EdpmNeutronSriovAgentImage
  edpmServiceType: neutron-sriov
