apiVersion: dataplane.openstack.org/v1beta1
kind: OpenStackDataPlaneService
metadata:
  name: neutron-ovn
spec:
  playbook: osp.edpm.neutron_ovn
  dataSources:
    - secretRef:
        name: neutron-ovn-agent-neutron-config
    - secretRef:
        name: nova-metadata-neutron-config
        optional: true
    - configMapRef:
        name: neutron-ovn-extra-config
        optional: true
  tlsCerts:
    default:
      contents:
      - dnsnames
      - ips
      networks:
      - ctlplane
      issuer: osp-rootca-issuer-ovn
      keyUsages:
        - digital signature
        - key encipherment
        - client auth
  caCerts: combined-ca-bundle
  containerImageFields:
  - EdpmNeutronOvnAgentImage
  edpmServiceType: neutron-ovn
