apiVersion: dataplane.openstack.org/v1beta1
kind: OpenStackDataPlaneService
metadata:
  name: derive-pci-devicespec
spec:
  playbook: osp.edpm.sriov_derive_device_spec
  edpmServiceType: derive-pci-devicespec
