apiVersion: dataplane.openstack.org/v1beta1
kind: OpenStackDataPlaneService
metadata:
  name: install-certs
spec:
  playbook: osp.edpm.install_certs
  addCertMounts: True
  edpmServiceType: install-certs
