apiVersion: dataplane.openstack.org/v1beta1
kind: OpenStackDataPlaneService
metadata:
  name: telemetry
spec:
  dataSources:
    - secretRef:
        name: ceilometer-compute-config-data
  playbook: osp.edpm.telemetry
  tlsCerts:
    default:
      contents:
      - ips
  caCerts: combined-ca-bundle
  containerImageFields:
  - CeilometerComputeImage
  - CeilometerIpmiImage
  - EdpmNodeExporterImage
