resources:
- ../crd/bases/operator.openstack.org_openstacks.yaml
- ../samples/operator_v1beta1_openstack.yaml

bases:
- manifests
- rbac
- deployment

patches:

# Injects our custom images (ENV variable settings)
- path: manager_operator_images.yaml
- path: default_images.yaml
