{{ range .ServiceOperators }}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    control-plane: controller-manager
    openstack.org/operator-name: {{ .Name }}
  name: {{ .Name }}-operator-controller-manager
  namespace: {{ .Namespace }}
spec:
  replicas: {{ .Deployment.Replicas }}
  selector:
    matchLabels:
      openstack.org/operator-name: {{ .Name }}
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        control-plane: controller-manager
        openstack.org/operator-name: {{ .Name }}
    spec:
      containers:
      - args:
        - --health-probe-bind-address=:8081
        - --metrics-bind-address=127.0.0.1:8080
        - --leader-elect
        command:
        - /manager
        env:
{{- range .Deployment.Manager.Env }}
        - name: {{ .Name }}
          value: '{{ .Value }}'
{{- end }}
        image: {{ .Deployment.Manager.Image }}
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        name: manager
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: {{ .Deployment.Manager.Resources.Limits.CPU }}
            memory: {{ .Deployment.Manager.Resources.Limits.Memory }}
          requests:
            cpu: {{ .Deployment.Manager.Resources.Requests.CPU }}
            memory: {{ .Deployment.Manager.Resources.Requests.Memory }}
        securityContext:
          allowPrivilegeEscalation: false
{{- if isEnvVarTrue .Deployment.Manager.Env "ENABLE_WEBHOOKS" }}
        volumeMounts:
        - mountPath: /tmp/k8s-webhook-server/serving-certs
          name: cert
          readOnly: true
{{- end }}
      securityContext:
        runAsNonRoot: true
      serviceAccountName: {{ .Name }}-operator-controller-manager
      terminationGracePeriodSeconds: 10
      tolerations:
{{- range .Deployment.Tolerations }}
      - key: "{{ .Key }}"
{{- if .Operator }}
        operator: "{{ .Operator }}"
{{- end }}
{{- if .Value }}
        value: "{{ .Value }}"
{{- end }}
{{- if .Effect }}
        effect: "{{ .Effect }}"
{{- end }}
{{- if .TolerationSeconds }}
        tolerationSeconds: {{ .TolerationSeconds }}
{{- end }}
{{- end }}
{{- if isEnvVarTrue .Deployment.Manager.Env "ENABLE_WEBHOOKS" }}
      volumes:
      - name: cert
        secret:
          defaultMode: 420
          secretName: {{ .Name }}-operator-webhook-server-cert
{{ end }}
---
{{ end }}
