---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-client-openstack-org-v1beta1-openstackclient
  failurePolicy: Fail
  name: mopenstackclient.kb.io
  rules:
  - apiGroups:
    - client.openstack.org
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - openstackclients
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-core-openstack-org-v1beta1-openstackcontrolplane
  failurePolicy: Fail
  name: mopenstackcontrolplane.kb.io
  rules:
  - apiGroups:
    - core.openstack.org
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - openstackcontrolplanes
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-core-openstack-org-v1beta1-openstackversion
  failurePolicy: Fail
  name: mopenstackversion.kb.io
  rules:
  - apiGroups:
    - core.openstack.org
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - openstackversions
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-dataplane-openstack-org-v1beta1-openstackdataplanedeployment
  failurePolicy: Fail
  name: mopenstackdataplanedeployment.kb.io
  rules:
  - apiGroups:
    - dataplane.openstack.org
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - openstackdataplanedeployments
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-dataplane-openstack-org-v1beta1-openstackdataplanenodeset
  failurePolicy: Fail
  name: mopenstackdataplanenodeset.kb.io
  rules:
  - apiGroups:
    - dataplane.openstack.org
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - openstackdataplanenodesets
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-dataplane-openstack-org-v1beta1-openstackdataplaneservice
  failurePolicy: Fail
  name: mopenstackdataplaneservice.kb.io
  rules:
  - apiGroups:
    - dataplane.openstack.org
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - openstackdataplaneservices
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-client-openstack-org-v1beta1-openstackclient
  failurePolicy: Fail
  name: vopenstackclient.kb.io
  rules:
  - apiGroups:
    - client.openstack.org
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - openstackclients
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-core-openstack-org-v1beta1-openstackcontrolplane
  failurePolicy: Fail
  name: vopenstackcontrolplane.kb.io
  rules:
  - apiGroups:
    - core.openstack.org
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - openstackcontrolplanes
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-core-openstack-org-v1beta1-openstackversion
  failurePolicy: Fail
  name: vopenstackversion.kb.io
  rules:
  - apiGroups:
    - core.openstack.org
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - openstackversions
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-dataplane-openstack-org-v1beta1-openstackdataplanedeployment
  failurePolicy: Fail
  name: vopenstackdataplanedeployment.kb.io
  rules:
  - apiGroups:
    - dataplane.openstack.org
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - openstackdataplanedeployments
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-dataplane-openstack-org-v1beta1-openstackdataplanenodeset
  failurePolicy: Fail
  name: vopenstackdataplanenodeset.kb.io
  rules:
  - apiGroups:
    - dataplane.openstack.org
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - openstackdataplanenodesets
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-dataplane-openstack-org-v1beta1-openstackdataplaneservice
  failurePolicy: Fail
  name: vopenstackdataplaneservice.kb.io
  rules:
  - apiGroups:
    - dataplane.openstack.org
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - openstackdataplaneservices
  sideEffects: None
