# This rule is not used by the project openstack-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over dataplane.openstack.org.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: openstack-operator
    app.kubernetes.io/managed-by: kustomize
  name: dataplane-openstackdataplanedeployment-admin-role
rules:
- apiGroups:
  - dataplane.openstack.org
  resources:
  - openstackdataplanedeployments
  verbs:
  - '*'
- apiGroups:
  - dataplane.openstack.org
  resources:
  - openstackdataplanedeployments/status
  verbs:
  - get
