apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: openstack-operator-controller-init
    app.kubernetes.io/managed-by: kustomize
  name: controller-init
  namespace: system
