apiVersion: core.openstack.org/v1beta1
kind: OpenStackControlPlane
metadata:
  name: openstack-collapsed-cell
spec:
  secret: osp-secret
  storageClass: local-storage
  keystone:
    template:
      containerImage: quay.io/tripleozedcentos9/openstack-keystone:current-tripleo
      databaseInstance: openstack
      secret: osp-secret
  mariadb:
    template:
      containerImage: quay.io/tripleozedcentos9/openstack-mariadb:current-tripleo
      storageRequest: 500M
  rabbitmq:
    templates:
      rabbitmq:
        replicas: 1
        #resources:
        #  requests:
        #    cpu: 500m
        #    memory: 1Gi
        #  limits:
        #    cpu: 800m
        #    memory: 1Gi
  memcached:
    enabled: true
    templates:
      memcached:
        containerImage: quay.io/tripleozedcentos9/openstack-memcached:current-tripleo
        replicas: 1
  placement:
    template:
      databaseInstance: openstack
      containerImage: quay.io/tripleozedcentos9/openstack-placement-api:current-tripleo
      secret: osp-secret
  glance:
    template:
      databaseInstance: openstack
      containerImage: quay.io/tripleozedcentos9/openstack-glance-api:current-tripleo
      storageClass: ""
      storageRequest: 10G
      glanceAPIInternal:
        containerImage: quay.io/tripleozedcentos9/openstack-glance-api:current-tripleo
      glanceAPIExternal:
        containerImage: quay.io/tripleozedcentos9/openstack-glance-api:current-tripleo
  cinder:
    template:
      cinderAPI:
        replicas: 1
        containerImage: quay.io/tripleozedcentos9/openstack-cinder-api:current-tripleo
      cinderScheduler:
        replicas: 1
        containerImage: quay.io/tripleozedcentos9/openstack-cinder-scheduler:current-tripleo
      cinderBackup:
        replicas: 0 # backend needs to be configured
        containerImage: quay.io/tripleozedcentos9/openstack-cinder-backup:current-tripleo
      cinderVolumes:
        volume1:
          containerImage: quay.io/tripleozedcentos9/openstack-cinder-volume:current-tripleo
          replicas: 0 # backend needs to be configured
  ovn:
    template:
      ovnDBCluster:
        ovndbcluster-nb:
          replicas: 1
          containerImage: quay.io/tripleozedcentos9/openstack-ovn-nb-db-server:current-tripleo
          dbType: NB
          storageRequest: 10G
        ovndbcluster-sb:
          replicas: 1
          containerImage: quay.io/tripleozedcentos9/openstack-ovn-sb-db-server:current-tripleo
          dbType: SB
          storageRequest: 10G
      ovnNorthd:
        replicas: 1
        containerImage: quay.io/tripleozedcentos9/openstack-ovn-northd:current-tripleo
  ovs:
    template:
      ovsContainerImage: "quay.io/skaplons/ovs:latest"
      ovnContainerImage: "quay.io/tripleozedcentos9/openstack-ovn-controller:current-tripleo"
      external-ids:
        system-id: "random"
        ovn-bridge: "br-int"
        ovn-encap-type: "geneve"
  neutron:
    template:
      databaseInstance: openstack
      containerImage: quay.io/tripleozedcentos9/openstack-neutron-server:current-tripleo
      secret: osp-secret
  nova:
    template:
      secret: osp-secret
      # This creates a collapsed cell deployment same as what OSP17 does by
      # default. The conductor in cell1 acts as both the cell conductor and the
      # super conductor hence cell0 conductor is disabled. Also in this
      # deployment both the top level services and cell1 service will share the
      # same message bus and database service instance so there is no cell
      # separation implemented.
      cellTemplates:
          cell0:
            cellDatabaseUser: nova_cell0
            conductorServiceTemplate:
              replicas: 0
            hasAPIAccess: true
          cell1:
            cellDatabaseUser: nova_cell1
            conductorServiceTemplate:
              replicas: 1
            hasAPIAccess: true
  ironic:
    template:
      databaseInstance: openstack
      ironicAPI:
        replicas: 1
        containerImage: quay.io/tripleozedcentos9/openstack-ironic-api:current-tripleo
      ironicConductors:
      - replicas: 1
        containerImage: quay.io/tripleozedcentos9/openstack-ironic-conductor:current-tripleo
        pxeContainerImage: quay.io/tripleozedcentos9/openstack-ironic-pxe:current-tripleo
        storageRequest: 10G
      ironicInspector:
        replicas: 1
        containerImage: quay.io/tripleozedcentos9/openstack-ironic-inspector:current-tripleo
        pxeContainerImage: quay.io/tripleozedcentos9/openstack-ironic-pxe:current-tripleo
      secret: osp-secret
