apiVersion: core.openstack.org/v1beta1
kind: OpenStackControlPlane
metadata:
  name: openstack-network-isolation
spec:
  secret: osp-secret
  storageClass: local-storage
  cinder:
    template:
      databaseInstance: openstack
      secret: osp-secret
      cinderAPI:
        containerImage: quay.io/tripleozedcentos9/openstack-cinder-api:current-tripleo
        externalEndpoints:
        - endpoint: internal
          ipAddressPool: internalapi
          loadBalancerIPs:
          - 172.17.0.80
      cinderBackup:
        containerImage: quay.io/tripleozedcentos9/openstack-cinder-backup:current-tripleo
        networkAttachments:
        - storage
        replicas: 0 # backend needs to be configured
      cinderScheduler:
        containerImage: quay.io/tripleozedcentos9/openstack-cinder-scheduler:current-tripleo
      cinderVolumes:
        volume1:
          containerImage: quay.io/tripleozedcentos9/openstack-cinder-volume:current-tripleo
          networkAttachments:
          - storage
          replicas: 0 # backend needs to be configured
  glance:
    template:
      databaseInstance: openstack
      containerImage: quay.io/tripleozedcentos9/openstack-glance-api:current-tripleo
      storageClass: ""
      storageRequest: 10G
      glanceAPIInternal:
        containerImage: quay.io/tripleozedcentos9/openstack-glance-api:current-tripleo
        externalEndpoints:
        - endpoint: internal
          ipAddressPool: internalapi
          loadBalancerIPs:
          - 172.17.0.80
        networkAttachments:
        - storage
      glanceAPIExternal:
        containerImage: quay.io/tripleozedcentos9/openstack-glance-api:current-tripleo
        networkAttachments:
        - storage
  keystone:
    template:
      containerImage: quay.io/tripleozedcentos9/openstack-keystone:current-tripleo
      databaseInstance: openstack
      secret: osp-secret
      externalEndpoints:
      - endpoint: internal
        ipAddressPool: internalapi
        loadBalancerIPs:
        - 172.17.0.80
  mariadb:
    templates:
      openstack:
        containerImage: quay.io/tripleozedcentos9/openstack-mariadb:current-tripleo
        storageRequest: 500M
  memcached:
    enabled: true
    templates:
      memcached:
        containerImage: quay.io/tripleozedcentos9/openstack-memcached:current-tripleo
        replicas: 1
  neutron:
    template:
      databaseInstance: openstack
      containerImage: quay.io/tripleozedcentos9/openstack-neutron-server:current-tripleo
      secret: osp-secret
      externalEndpoints:
      - endpoint: internal
        ipAddressPool: internalapi
        loadBalancerIPs:
        - 172.17.0.80
      networkAttachments:
      - internalapi
  nova:
    template:
      apiServiceTemplate:
        externalEndpoints:
        - endpoint: internal
          ipAddressPool: internalapi
          loadBalancerIPs:
          - 172.17.0.80
      secret: osp-secret
  manila:
    template:
      manilaAPI:
        replicas: 1
        containerImage: quay.io/tripleozedcentos9/openstack-manila-api:current-tripleo
        externalEndpoints:
        - endpoint: internal
          ipAddressPool: internalapi
          loadBalancerIPs:
          - 172.17.0.80
        networkAttachments:
        - internalapi
      manilaScheduler:
        replicas: 1
        containerImage: quay.io/tripleozedcentos9/openstack-manila-scheduler:current-tripleo
        networkAttachments:
        - internalapi
      manilaShares:
        share1:
          containerImage: quay.io/tripleozedcentos9/openstack-manila-share:current-tripleo
          replicas: 1
          networkAttachments:
          - internalapi
  ovn:
    template:
      ovnDBCluster:
        ovndbcluster-nb:
          containerImage: quay.io/tripleozedcentos9/openstack-ovn-nb-db-server:current-tripleo
          dbType: NB
          storageRequest: 10G
          networkAttachment: internalapi
        ovndbcluster-sb:
          containerImage: quay.io/tripleozedcentos9/openstack-ovn-sb-db-server:current-tripleo
          dbType: SB
          storageRequest: 10G
          networkAttachment: internalapi
      ovnNorthd:
        containerImage: quay.io/tripleozedcentos9/openstack-ovn-northd:current-tripleo
        networkAttachment: internalapi
  ovs:
    template:
      ovsContainerImage: "quay.io/skaplons/ovs:latest"
      ovnContainerImage: "quay.io/tripleozedcentos9/openstack-ovn-controller:current-tripleo"
      external-ids:
        system-id: "random"
        ovn-bridge: "br-int"
        ovn-encap-type: "geneve"
      networkAttachment: internalapi
  placement:
    template:
      containerImage: quay.io/tripleozedcentos9/openstack-placement-api:current-tripleo
      databaseInstance: openstack
      secret: osp-secret
      externalEndpoints:
      - endpoint: internal
        ipAddressPool: internalapi
        loadBalancerIPs:
        - 172.17.0.80
  rabbitmq:
    templates:
      rabbitmq:
        externalEndpoint:
          loadBalancerIPs:
          - 172.17.0.85
          ipAddressPool: internalapi
          sharedIP: false
      rabbitmq-cell1:
        externalEndpoint:
          loadBalancerIPs:
          - 172.17.0.86
          ipAddressPool: internalapi
          sharedIP: false
  ironic:
    enabled: false
    template:
      databaseInstance: openstack
      ironicAPI:
        replicas: 1
        containerImage: quay.io/tripleozedcentos9/openstack-ironic-api:current-tripleo
      ironicConductors:
      - replicas: 1
        containerImage: quay.io/tripleozedcentos9/openstack-ironic-conductor:current-tripleo
        pxeContainerImage: quay.io/tripleozedcentos9/openstack-ironic-pxe:current-tripleo
        storageRequest: 10G
      ironicInspector:
        replicas: 1
        containerImage: quay.io/tripleozedcentos9/openstack-ironic-inspector:current-tripleo
        pxeContainerImage: quay.io/tripleozedcentos9/openstack-ironic-pxe:current-tripleo
      secret: osp-secret
